### PR TITLE
VSCode 1.94.0^Neon Dreams Undefined 'filename' Fix

### PR DESCRIPTION
**Pull request by Raezard77**

### CODE REVIEW

**Review by tchars — APPROVED** [review]

**Comment by eli-fusionary** [comment]
Just coming in here to comment this also fixes the error on MacOS

**Comment by aihaddad** [comment]
Tried this and while enabling the Neon effect works (on MacOS), the brightness setting is somehow not effective.

**Comment by MNS26** [comment]
found this one just now
https://github.com/robb0wen/synthwave-vscode/issues/317
i had updated vscode and got it too... this fixed it for me

**Comment by robb0wen** [comment]
#327 Was merged and fixed the same issue, so I'm closing this. Thanks for taking a look though, I do appreciate it.

**Pull request closed without merging**
