### PR TITLE
Add details steps for `Reload Custom CSS and JS`

### PR DESCRIPTION
**Pull request by vuchan**

### CODE REVIEW

**Comment by vuchan** [comment]
@JohnArcher  thanks, because i am not a native English speaker, so may there has some typo or grammar errors. If you have time, you can edit those words. i ever met same situation at StackOverflow.com. the native English speaker modified the all of answer text of mine.

Thanks Again.

**Comment by JohnArcher** [comment]
I am sorry, I hope you know it wasn't meant in a mean way! The problem is, I am also no native English speaker, so I am not the right person to correct it. I can only see that there is something wrong with grammar, but most time I am not able to transfer it to proper English.

**Comment by vuchan** [comment]
ok, i got it. it is ok.

**Comment by vuchan** [comment]
but your English is very good than mine, haha.....

**Pull request closed without merging**
