### PR TITLE
Add 'neon flicker'

### PR DESCRIPTION
**Pull request by josephfusco**
This adds a subtle flicker animation to .mtk7 which seemed to be a good balance compared to the other elements with the neon glow text-shadow.

Thinking about this more this flicker might not be for everyone. I currently have it in the primary file. Thoughts on updating this PR to have the following structure?

+ synthwave84.css
+ syntwave84-no-flicker.css
+ synthwave84-no-flicker-no-glow.css

Another weird quirk is that although the animation-fill-mode is 'forwards', if one of the animated elements leaves the viewport and is scrolled back into view the animation restarts which I am not a fan of. This also seems to happen when you hover the animated element after the animation completes. IMO the animation should only happen once with a not-so-common event (like only animated when the file initially opens).

## Warning

This preview may potentially trigger seizures for people with photosensitive epilepsy.

Scroll down to view the gif

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

↓

### CODE REVIEW

**Comment by robb0wen** [comment]
Whilst I like the _idea_ of the flickering, and your implementation of it, I don't feel that it belongs in the main repo. I feel like the glow-enabled theme should retain practicality and, as the glow was already something of a novelty, I'd rather not push it further into that territory.

**Comment by josephfusco** [comment]
@robb0wen Understandable. Thanks for the consideration & great work on this!

**Comment by pulberg** [comment]
couldn't it just be a param in the users settings.json to enable/disable the flicker effect?

**Comment by josephfusco** [comment]
@pulberg Unfortunately I don't believe the custom css extension that this is dependent on has that ability as the user needs to define where the custom css lives on their system.

**Comment by robb0wen** [comment]
Yeah, as @pulberg says, the glow CSS is outside of how VS Code normally does things so it would need to be edited manually. I'd rather leave this kind of thing up to the individual user to implement to their own tastes

**Pull request closed without merging**
