### PR TITLE
Fix low contrast and non-visible colors

### PR DESCRIPTION
**Pull request by moxwel**
This fixes some details related to the low contrast of comments, related to #124

> Before / After
> comp

And a little bug in the integrated terminal: the selection was _no-visible_, now is visible.

> Before / After
> bug

### CODE REVIEW

**Comment by moxwel** [comment]
Also, a little fix to the background color when grouping editors. Now it have more contrast too:

> Before
> before

> After
> after

**Comment by moxwel** [comment]
The `diffEditor` colors now have more contrast.

> Before / After
> diff

**Comment by moxwel** [comment]
Command palette active selection now are more visible

> Before / After
> diff

**Comment by aasutossh** [comment]
Why isn't this getting merged?

**Comment by moxwel** [comment]
> Why isn't this getting merged?

@aasutossh It seems we have to wait... @robb0wen decides if this PR will be merged _(or not)_.

**Comment by aasutossh** [comment]
How do I use your version of the theme?

**Comment by moxwel** [comment]
> How do I use your version of the theme?

@aasutossh Its a little tricky, but you can copy/paste the edited [synthwave-color-theme.json](https://github.com/robb0wen/synthwave-vscode/blob/267e54ef1cc66d7e9d69a7d2879f84b751603e59/themes/synthwave-color-theme.json) in the folder where you have the theme installed on VSCode.

On Windows, the file is located at `%USERPROFILE%\.vscode\extensions\robbowen.synthwave-vscode-0.1.6\themes`.

**Comment by aasutossh** [comment]
Gonna use it until it gets merged.

**Comment by dominiquediotte** [comment]
I completely approve the higher contrast element. Currently, it's hard to see things.

**Comment by robb0wen** [comment]
Apologies for the delay on merging this. Combination of being very busy with my day-job and Covid lockdown. Anyhow, this is a fantastic help, thanks.

**Comment by moxwel** [comment]
No problem! And thank you 😊

**Comment by aasutossh** [comment]
Finally. Yay yay yay!!! <3

**Pull request merged**
